# Generated by Django 6.0.7 on 2026-07-08 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='customer_name',
            field=models.CharField(blank=True, db_index=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='payment_method',
            field=models.CharField(choices=[('NONE', 'None'), ('CASH', 'Cash'), ('MPESA', 'M-PESA'), ('CREDIT', 'Credit / Tab')], default='NONE', max_length=20),
        ),
    ]
