# Generated by Django 6.0.7 on 2026-07-08 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='mpesa_reference',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True),
        ),
    ]
